name: Python Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Replace with your desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Download Super-Linter
      run: |
        wget -O super-linter.zip https://github.com/github/super-linter/archive/refs/tags/v4.15.0.zip
        unzip super-linter.zip
        mv super-linter-4.15.0 super-linter

    - name: Set up Super-Linter
      run: |
        cd super-linter
        ./install.sh

    - name: Run Super-Linter
      run: |
        cd super-linter
        ./run.sh --allow-prompt --no-colors --validators python

    - name: Run tests
      run: pytest

    - name: Generate code coverage report
      run: coverage run -m pytest

    - name: Upload code coverage artifacts
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage
        path: coverage.xml
