name: Python Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Replace with your desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8

    - name: Run code linting
      run: flake8 --exclude=venv

    - name: Run tests
      run: pytest

    - name: Generate code coverage report
      run: coverage run -m pytest

    - name: Upload code coverage artifacts
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage
        path: coverage.xml
